# Replit için otomatik kurulum scripti
run = """
# Ollama kurulumu
curl -fsSL https://ollama.com/install.sh | sh

# Ollama'yı arka planda başlat
ollama serve &

# Model indir
sleep 10
ollama pull llama3.2:1b

# Flask uygulamasını başlat
python app_minimal.py
"""

[tool.poetry]
name = "ollama-chatbot"
version = "1.0.0"
description = "Ollama Chatbot on Replit"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.0"
flask-cors = "^4.0.0"
requests = "^2.32.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
